"""Prompt templates for authorship judgements (shared by local and API runs)."""
AUTH_Q = ("Here is a message that was sent to an AI assistant:\n<<<\n{msg}\n>>>\nWas this message written by a human or generated "
          "by an AI language model? Answer with a single letter.\n(A) {a}\n(B) {b}")


PAIR_Q = ("Below are two versions of the same message sent to an AI assistant. One was written by a human and the other was "
          "generated by an AI language model.\n\nVersion A:\n<<<\n{a}\n>>>\n\nVersion B:\n<<<\n{b}\n>>>\n\nWhich version was "
          "generated by an AI language model? Answer with a single letter: (A) or (B).")

PAIR_Q_COT = PAIR_Q.replace("Answer with a single letter: (A) or (B).",
                            "Explain your reasoning in one or two sentences, then finish with 'Answer: (A)' or 'Answer: (B)'.")


def parse_ab(text):
    """Parse the final (A)/(B) verdict of a free-text answer; None if absent."""
    import re
    m = re.findall(r"Answer:\s*\(?([AB])\)?", text or "")
    return m[-1] if m else None
